services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cards-site:latest
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://postgres:example@db:5432/postgres?sslmode=disable
    command: ["./cards-site", "--config", "cmd/web/config.yaml"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: cards-site:test
    command: ["go", "test", "./..."]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_DSN=postgres://postgres:example@db:5432/postgres?sslmode=disable

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./internal/migrations:/migrations
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    image: migrate/migrate:v4.15.2
    depends_on:
      - db
    environment:
      - DB_DSN=${DB_DSN}
    volumes:
      - ./internal/migrations:/migrations

volumes:
  db_data: