FROM migrate/migrate:v4.15.2

# pg_isready
RUN apk add --no-cache postgresql-client

ENTRYPOINT [ "sh", "-c", "until pg_isready -h db -p 5432; do sleep 1; done; migrate -path=migrations -database \"${DB_DSN}\" up "]